# File generated from our OpenAPI spec by Stainless. See CONTRIBUTING.md for details.

from __future__ import annotations

from . import webhook_event_type, webhook_list_event_types_response
from .. import _compat
from .api_meta import APIMeta as APIMeta
from .template import Template as Template
from .error_detail import ErrorDetail as ErrorDetail
from .tcr_vertical import TcrVertical as TcrVertical
from .message_event import MessageEvent as MessageEvent
from .user_response import UserResponse as UserResponse
from .profile_detail import ProfileDetail as ProfileDetail
from .template_event import TemplateEvent as TemplateEvent
from .pagination_meta import PaginationMeta as PaginationMeta
from .contact_response import ContactResponse as ContactResponse
from .profile_settings import ProfileSettings as ProfileSettings
from .webhook_response import WebhookResponse as WebhookResponse
from .user_invite_params import UserInviteParams as UserInviteParams
from .user_list_response import UserListResponse as UserListResponse
from .user_remove_params import UserRemoveParams as UserRemoveParams
from .webhook_event_type import WebhookEventType as WebhookEventType
from .contact_list_params import ContactListParams as ContactListParams
from .destination_country import DestinationCountry as DestinationCountry
from .message_send_params import MessageSendParams as MessageSendParams
from .template_body_param import TemplateBodyParam as TemplateBodyParam
from .webhook_list_params import WebhookListParams as WebhookListParams
from .webhook_test_params import WebhookTestParams as WebhookTestParams
from .api_response_of_user import APIResponseOfUser as APIResponseOfUser
from .api_response_webhook import APIResponseWebhook as APIResponseWebhook
from .me_retrieve_response import MeRetrieveResponse as MeRetrieveResponse
from .template_list_params import TemplateListParams as TemplateListParams
from .api_response_template import APIResponseTemplate as APIResponseTemplate
from .contact_create_params import ContactCreateParams as ContactCreateParams
from .contact_delete_params import ContactDeleteParams as ContactDeleteParams
from .contact_list_response import ContactListResponse as ContactListResponse
from .contact_update_params import ContactUpdateParams as ContactUpdateParams
from .inbound_message_event import InboundMessageEvent as InboundMessageEvent
from .message_event_payload import MessageEventPayload as MessageEventPayload
from .message_send_response import MessageSendResponse as MessageSendResponse
from .payment_details_param import PaymentDetailsParam as PaymentDetailsParam
from .profile_create_params import ProfileCreateParams as ProfileCreateParams
from .profile_delete_params import ProfileDeleteParams as ProfileDeleteParams
from .profile_list_response import ProfileListResponse as ProfileListResponse
from .profile_update_params import ProfileUpdateParams as ProfileUpdateParams
from .template_button_param import TemplateButtonParam as TemplateButtonParam
from .template_footer_param import TemplateFooterParam as TemplateFooterParam
from .template_header_param import TemplateHeaderParam as TemplateHeaderParam
from .webhook_create_params import WebhookCreateParams as WebhookCreateParams
from .webhook_list_response import WebhookListResponse as WebhookListResponse
from .webhook_test_response import WebhookTestResponse as WebhookTestResponse
from .webhook_update_params import WebhookUpdateParams as WebhookUpdateParams
from .number_lookup_response import NumberLookupResponse as NumberLookupResponse
from .tcr_brand_relationship import TcrBrandRelationship as TcrBrandRelationship
from .template_create_params import TemplateCreateParams as TemplateCreateParams
from .template_delete_params import TemplateDeleteParams as TemplateDeleteParams
from .template_event_payload import TemplateEventPayload as TemplateEventPayload
from .template_list_response import TemplateListResponse as TemplateListResponse
from .template_update_params import TemplateUpdateParams as TemplateUpdateParams
from .api_response_of_contact import APIResponseOfContact as APIResponseOfContact
from .brands_brand_data_param import BrandsBrandDataParam as BrandsBrandDataParam
from .contact_message_summary import ContactMessageSummary as ContactMessageSummary
from .profile_complete_params import ProfileCompleteParams as ProfileCompleteParams
from .template_variable_param import TemplateVariableParam as TemplateVariableParam
from .user_update_role_params import UserUpdateRoleParams as UserUpdateRoleParams
from .brand_contact_info_param import BrandContactInfoParam as BrandContactInfoParam
from .conversation_list_params import ConversationListParams as ConversationListParams
from .brand_business_info_param import BrandBusinessInfoParam as BrandBusinessInfoParam
from .destination_country_param import DestinationCountryParam as DestinationCountryParam
from .profile_complete_response import ProfileCompleteResponse as ProfileCompleteResponse
from .template_definition_param import TemplateDefinitionParam as TemplateDefinitionParam
from .billing_contact_info_param import BillingContactInfoParam as BillingContactInfoParam
from .conversation_messages_list import ConversationMessagesList as ConversationMessagesList
from .webhook_list_events_params import WebhookListEventsParams as WebhookListEventsParams
from .authentication_config_param import AuthenticationConfigParam as AuthenticationConfigParam
from .brand_compliance_info_param import BrandComplianceInfoParam as BrandComplianceInfoParam
from .template_body_content_param import TemplateBodyContentParam as TemplateBodyContentParam
from .template_button_props_param import TemplateButtonPropsParam as TemplateButtonPropsParam
from .webhook_list_events_response import WebhookListEventsResponse as WebhookListEventsResponse
from .webhook_rotate_secret_params import WebhookRotateSecretParams as WebhookRotateSecretParams
from .webhook_toggle_status_params import WebhookToggleStatusParams as WebhookToggleStatusParams
from .inbound_message_event_payload import InboundMessageEventPayload as InboundMessageEventPayload
from .api_response_of_profile_detail import APIResponseOfProfileDetail as APIResponseOfProfileDetail
from .webhook_rotate_secret_response import WebhookRotateSecretResponse as WebhookRotateSecretResponse
from .message_retrieve_status_response import MessageRetrieveStatusResponse as MessageRetrieveStatusResponse
from .conversation_list_messages_params import ConversationListMessagesParams as ConversationListMessagesParams
from .webhook_list_event_types_response import WebhookListEventTypesResponse as WebhookListEventTypesResponse
from .message_retrieve_activities_response import MessageRetrieveActivitiesResponse as MessageRetrieveActivitiesResponse
from .api_response_of_contact_message_summary import (
    APIResponseOfContactMessageSummary as APIResponseOfContactMessageSummary,
)
from .api_response_of_conversation_messages_list import (
    APIResponseOfConversationMessagesList as APIResponseOfConversationMessagesList,
)

# Rebuild cyclical models only after all modules are imported.
# This ensures that, when building the deferred (due to cyclical references) model schema,
# Pydantic can resolve the necessary references.
# See: https://github.com/pydantic/pydantic/issues/11250 for more context.
if _compat.PYDANTIC_V1:
    webhook_event_type.WebhookEventType.update_forward_refs()  # type: ignore
    webhook_list_event_types_response.WebhookListEventTypesResponse.update_forward_refs()  # type: ignore
else:
    webhook_event_type.WebhookEventType.model_rebuild(_parent_namespace_depth=0)
    webhook_list_event_types_response.WebhookListEventTypesResponse.model_rebuild(_parent_namespace_depth=0)
